### ISSUE TITLE
SSL 인증서 검토

### ISSUE THREAD

**Issue by level120** [Team-Maple-Leaf/MapleJudgePlatform-backend#12]
다음 주소에 대해 인증서 발급
* URI: api.maple-leaf.dev
* Tool: Let's encrypt

만약에 와일드카드를 적용할 수 있다면 아래 주소에 대해 인증서 발급하는 것으로 변경
* URL: *.maple-leaf.dev

**Comment by leedonggyu1848** [comment]
관련 링크
- https://hub.docker.com/r/certbot/certbot
- https://stackoverflow.com/questions/66638368/how-to-do-auto-renewal-of-tls-certificates-with-certbot

**Comment by level120** [comment]
https://github.com/Team-Maple-Leaf/MapleJudgePlatform/pull/48
